# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
    ]
