# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filepath',
        ),
        migrations.AddField(
            model_name='file',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='pid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='scantype',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
