# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181002_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='scantype',
        ),
    ]
