# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_file_scantype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='mp',
        ),
    ]
