# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-03 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_file_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='apspine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='combination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='dualfemur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='fracture',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lva',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='scantype',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='t7',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='tscore',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='zscore',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='age',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
