# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_patient_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='file_path',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
